{
  description = "Public API definitions";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    systems.url = "github:UnstoppableMango/nix-systems";
    flake-parts.url = "github:hercules-ci/flake-parts";

    a2b = {
      url = "github:UnstoppableMango/a2b";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.systems.follows = "systems";
      inputs.flake-parts.follows = "flake-parts";
      inputs.mangopkgs.follows = "mangopkgs";
      inputs.treefmt-nix.follows = "treefmt-nix";
    };

    # a2b's input rather than one this flake evaluates, declared here so a
    # consumer points it at their own mangopkgs with one `follows` on this
    # flake. Reaching it through a2b instead means a nested override in every
    # consumer, and a second mangopkgs in their lock until someone writes one.
    mangopkgs = {
      url = "github:unmango/pkgs";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.systems.follows = "systems";
      inputs.flake-parts.follows = "flake-parts";
      inputs.treefmt-nix.follows = "treefmt-nix";
    };

    googleapis = {
      url = "github:googleapis/googleapis";
      flake = false;
    };

    # Tag-pinned, so `nix flake update` leaves it alone. Bumping is an edit to
    # this URL followed by `nix flake lock --update-input apimachinery`.
    apimachinery = {
      url = "github:kubernetes/apimachinery/v0.36.4";
      flake = false;
    };

    # Tag-pinned like apimachinery: proto/unmango is generated by this tdl, so
    # a bump is a regeneration and belongs in its own commit. Its nixpkgs is
    # its own: tdl needs a newer Go than this flake's nixpkgs may carry.
    tdl = {
      url = "github:UnstoppableMango/tdl/v0.2.14";
      inputs.systems.follows = "systems";
      inputs.flake-parts.follows = "flake-parts";
      inputs.treefmt-nix.follows = "treefmt-nix";
    };

    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    inputs@{ flake-parts, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      systems = import inputs.systems;
      imports = [
        inputs.systems.flakeModule
        inputs.treefmt-nix.flakeModule
        inputs.tdl.flakeModules.default
      ];

      perSystem =
        {
          config,
          inputs',
          pkgs,
          lib,
          ...
        }:
        let
          inherit (lib.attrsets) recurseIntoAttrs;

          # tdl file names relative to the repo root, which is where the checks
          # run: out("proto") and the shim imports resolve from there.
          tdlFiles =
            dir:
            map (lib.removePrefix "${toString ./.}/") (
              lib.filter (lib.hasSuffix ".tdl") (map toString (lib.filesystem.listFilesRecursive dir))
            );
          unmangoApis = pkgs.callPackage ./nix {
            bufLib = inputs'.a2b.legacyPackages.lib.buf;
            googleapisSrc = inputs.googleapis;
            apimachinerySrc = inputs.apimachinery;
          };
        in
        {
          packages.default = unmangoApis.generated;
          packages.update = pkgs.callPackage ./nix/update.nix { };
          legacyPackages.unmangoApis = recurseIntoAttrs unmangoApis;

          # k8s.io imports resolve only inside the workspace, so the repo-root
          # buf.yaml cannot be linted on its own.
          checks.buf-lint = pkgs.runCommand "buf-lint" { } ''
            export HOME="$(mktemp -d)"
            ${pkgs.buf}/bin/buf lint ${unmangoApis.workspace}
            touch "$out"
          '';

          # AIP conformance. The rule disables in api-linter.yaml are the
          # divergences docs/aip.md declines; anything else is a finding.
          checks.api-linter = unmangoApis.apiLinter;

          # The identity band is a convention repeated across every resource
          # rather than a shared message type, so nothing in the compiler stops
          # a new kind from putting labels at 3. This does.
          checks.field-bands = pkgs.runCommand "field-bands" { } ''
            ${pkgs.python3}/bin/python3 ${./hack/check-field-bands.py} ${./proto}
            touch "$out"
          '';

          # tdl-gen runs `tdl gen --verify`, failing when proto/unmango differs
          # from what tdl/ generates.
          tdl = {
            enable = true;
            package = inputs'.tdl.packages.default;
            src = lib.fileset.toSource {
              root = ./.;
              fileset = lib.fileset.unions [
                ./tdl
                ./proto
              ];
            };
            files = tdlFiles ./tdl;
            gen.files = tdlFiles ./tdl/unmango;
          };

          devShells.default = pkgs.mkShellNoCC {
            inputsFrom = [ config.devShells.tdl ];
            packages = with pkgs; [
              api-linter
              buf
              gnumake
              nixfmt
            ];
          };

          # Generated by tdl, whose output buf format would reflow, and tdl-gen
          # would then report as drift.
          treefmt.settings.global.excludes = [ "proto/unmango/**" ];

          treefmt.programs = {
            actionlint.enable = true;
            buf.enable = true;
            mdformat.enable = true;
            nixfmt.enable = true;

            yamllint = {
              enable = true;
              settings.document-start = "disable";
            };
          };
        };
    };
}
